name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false # Important to prevent using the default token
          fetch-depth: 0             # Fetch all history for all branches and tags

      - name: Set Up Git Configuration
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/DataExpert-io/data-engineer-handbook.git
          git fetch upstream

      - name: Sync with Upstream using Rebase
        run: |
          git checkout main
          git pull --rebase upstream main --allow-unrelated-histories
          git push origin main --force-with-lease
